import type {
  EmployeeProfile,
  MachineTelemetry,
  ProcessTest,
  InventoryChamber,
  FefoCrateItem,
  SupplyBatch,
  CashFlowMetrics,
  PipelineStage,
  PlantAlert,
  WorkerGrievance,
} from "./types";

/**
 * 5 Employee Ranks reflecting distinct organizational layers in Indian Food MSMEs.
 * Provides Role-Based Access Control (RBAC) to enforce security, transparency, and operational clarity.
 */
export const EMPLOYEE_PROFILES: EmployeeProfile[] = [
  {
    id: "EMP-R1",
    name: "Ramesh Kumar",
    role: "Line Operator & Cleansing Tech",
    rank: 1,
    department: "Floor Operations",
    shift: "Morning Shift (07:00 - 15:30)",
    badgeColor: "#64748B",
    permissions: {
      canViewSOPs: true,
      canOperateMachines: true,
      canRunQualityTests: false,
      canSignOffCompliance: false,
      canViewMaintenanceLogs: true,
      canEditMaintenanceSchedules: false,
      canViewSupplyChain: false,
      canApproveProcurement: false,
      canViewCashFlow: false,
      canAccessBankFinancing: false,
      canViewExecutiveReports: false,
    },
  },
  {
    id: "EMP-R2",
    name: "Priya Sharma",
    role: "Quality & Cold-Chain Inspector",
    rank: 2,
    department: "Quality Assurance & Compliance",
    shift: "General Shift (08:30 - 17:00)",
    badgeColor: "#0284C7",
    permissions: {
      canViewSOPs: true,
      canOperateMachines: false,
      canRunQualityTests: true,
      canSignOffCompliance: true,
      canViewMaintenanceLogs: true,
      canEditMaintenanceSchedules: false,
      canViewSupplyChain: true,
      canApproveProcurement: false,
      canViewCashFlow: false,
      canAccessBankFinancing: false,
      canViewExecutiveReports: false,
    },
  },
  {
    id: "EMP-R3",
    name: "Amit Patel",
    role: "Shift Supervisor & Plant Engineer",
    rank: 3,
    department: "Maintenance & Production Engineering",
    shift: "Production Lead Shift (07:00 - 19:00)",
    badgeColor: "#D97706",
    permissions: {
      canViewSOPs: true,
      canOperateMachines: true,
      canRunQualityTests: true,
      canSignOffCompliance: true,
      canViewMaintenanceLogs: true,
      canEditMaintenanceSchedules: true,
      canViewSupplyChain: true,
      canApproveProcurement: false,
      canViewCashFlow: false,
      canAccessBankFinancing: false,
      canViewExecutiveReports: false,
    },
  },
  {
    id: "EMP-R4",
    name: "Sunita Verma",
    role: "Supply Chain & Inventory Lead",
    rank: 4,
    department: "Logistics, Sourcing & Warehouse",
    shift: "General Shift (09:00 - 18:00)",
    badgeColor: "#1E4D2B",
    permissions: {
      canViewSOPs: true,
      canOperateMachines: false,
      canRunQualityTests: true,
      canSignOffCompliance: true,
      canViewMaintenanceLogs: true,
      canEditMaintenanceSchedules: false,
      canViewSupplyChain: true,
      canApproveProcurement: true,
      canViewCashFlow: true,
      canAccessBankFinancing: false,
      canViewExecutiveReports: true,
    },
  },
  {
    id: "EMP-R5",
    name: "Rajesh Mehra",
    role: "Plant Director & Managing Owner",
    rank: 5,
    department: "Executive & Strategic Finance",
    shift: "All Hours / Executive Oversight",
    badgeColor: "#C85A32",
    permissions: {
      canViewSOPs: true,
      canOperateMachines: true,
      canRunQualityTests: true,
      canSignOffCompliance: true,
      canViewMaintenanceLogs: true,
      canEditMaintenanceSchedules: true,
      canViewSupplyChain: true,
      canApproveProcurement: true,
      canViewCashFlow: true,
      canAccessBankFinancing: true,
      canViewExecutiveReports: true,
    },
  },
];

/**
 * Pipeline Productivity Stages:
 * Raw 100 → Wash 94 (-6 rejected) → Cold 88 (-6 spoiled) → Packed 88 → Dispatched 84
 * Footer summary: Raw 100 · WIP 94 · Finished 88 · Yield 88%
 */
export const PIPELINE_STAGES: PipelineStage[] = [
  {
    id: "raw",
    label: "Farm Harvest & Weighbridge",
    short: "1. Intake",
    count: 100,
    unit: "crates",
    icon: "tractor",
    sub: "Tractor trailer & drive-over weighbridge",
    tone: "leaf",
    targetTab: "supply",
  },
  {
    id: "wash",
    label: "Cleanroom Flume Washing",
    short: "2. Wash",
    count: 94,
    loss: "−6",
    unit: "crates",
    icon: "drop",
    sub: "108 ppm active Cl bubbling wash bath",
    tone: "teal",
    targetTab: "quality",
  },
  {
    id: "pack",
    label: "Cutting & MAP Packaging",
    short: "3. Pack",
    count: 88,
    loss: "−6",
    unit: "crates",
    icon: "box",
    sub: "Nitrogen MAP sealing (<1.0% O2) & lab QA",
    tone: "terra",
    targetTab: "machines",
  },
  {
    id: "cold",
    label: "3-Chamber Cold Complex",
    short: "4. Cold",
    count: 88,
    unit: "crates",
    icon: "snow",
    sub: "Pre-cooling, High-bay FEFO & blast holding",
    tone: "gold",
    targetTab: "inventory",
  },
  {
    id: "done",
    label: "Reefer Fleet & Mandi Hub",
    short: "5. Dispatch",
    count: 84,
    loss: "4 buf",
    unit: "crates",
    icon: "truck",
    sub: "40ft refrigerated trucks & wholesale mandi",
    tone: "ink",
    targetTab: "supply",
  },
];

/**
 * Dedicated Machine Hub Data.
 * Accurately models the low-investment, asset-light, and modular equipment.
 * MCH-05 is set to "alert" status to demonstrate live fault monitoring (Error E-42).
 */
export const MACHINES_DATA: MachineTelemetry[] = [
  {
    id: "MCH-01",
    name: "CoolBot AC Controlled Cold Chamber",
    category: "Cooling",
    status: "running",
    healthScore: 96,
    oee: 89.4,
    powerKw: 1.42,
    runtimeHours: 1420,
    lastServiceDate: "2026-09-02",
    nextServiceHours: 180,
    energySavingVsBaseline: "40% lower running electricity vs commercial walk-in",
    metrics: [
      { label: "Chamber Temp", value: "4.4", nominal: "4.0 - 6.5", unit: "°C", status: "ok" },
      { label: "Evaporator Fin Temp", value: "2.1", nominal: "1.5 - 3.5", unit: "°C", status: "ok" },
      { label: "Anti-Freeze Cycle", value: "Standby", nominal: "Active/Standby", unit: "state", status: "ok" },
      { label: "AC Current Draw", value: "6.2", nominal: "5.5 - 7.0", unit: "A", status: "ok" },
      { label: "Compressor Heat", value: "48", nominal: "< 65", unit: "°C", status: "ok" },
      { label: "Thermal Storage Buffer", value: "32", nominal: "> 24", unit: "hours", status: "ok" },
    ],
    pokaYokeGuides: [
      "Secondary fin temperature probe must be inserted precisely between aluminum fins (not touching copper tubes) to avoid false freezing triggers.",
      "CoolBot heater element must remain snugly wrapped around the AC thermostat sensor wire.",
      "Chamber double-strip PVC curtain must hang flush to avoid thermal leakage during crate loading.",
    ],
    sopSteps: [
      {
        step: 1,
        title: "Pre-Flight Visual Check",
        instruction: "Inspect air conditioner outdoor coil for dust blockage. Check door rubber gasket seal integrity.",
        safetyCheck: "Ensure 230V voltage stabilizer indicates green voltage between 210V and 240V.",
      },
      {
        step: 2,
        title: "Verify Sensor Clip Placement",
        instruction: "Confirm CoolBot frost sensor probe is placed 1 inch into the face of the cooling fins, 2 inches from the bottom right.",
        safetyCheck: "Never bend cooling fins sharply; use fin comb if bent.",
      },
      {
        step: 3,
        title: "Staggered Crate Infeed",
        instruction: "Load crates in batches not exceeding 20 crates/hour to prevent core thermal shock excursions.",
        safetyCheck: "Leave a minimum 10 cm perimeter airway between crates and wall panels.",
      },
    ],
    provenance: "SOURCE",
  },
  {
    id: "MCH-02",
    name: "Sanitizing Dip Station & Agitator",
    category: "Cleansing",
    status: "running",
    healthScore: 92,
    oee: 84.1,
    powerKw: 0.75,
    runtimeHours: 680,
    lastServiceDate: "2026-09-08",
    nextServiceHours: 120,
    energySavingVsBaseline: "Uses passive gravity filtration with low-kW circulating pump",
    metrics: [
      { label: "Free Chlorine", value: "108", nominal: "100 - 150", unit: "ppm", status: "ok" },
      { label: "Water Temp", value: "18.2", nominal: "15 - 22", unit: "°C", status: "ok" },
      { label: "Bath pH", value: "6.8", nominal: "6.5 - 7.5", unit: "pH", status: "ok" },
      { label: "Agitator Flow", value: "18.5", nominal: "15 - 25", unit: "L/min", status: "ok" },
      { label: "Dip Cycle Timer", value: "120", nominal: "120", unit: "sec", status: "ok" },
    ],
    pokaYokeGuides: [
      "Automatic digital timer lock prevents crate basket extraction prior to the mandatory 120-second immersion.",
      "Dual-chamber rinse: Stage 1 removes soil sediments; Stage 2 applies sanitizing solution with auto-dosed sodium hypochlorite.",
      "Photo-illustrated SOP chart affixed directly above basin at eye level for multilingual workforce.",
    ],
    sopSteps: [
      {
        step: 1,
        title: "Test Solution Titration",
        instruction: "Dip chlorine test strip into Stage 2 tank for 5 seconds. Match color pad against 100-150 ppm standard.",
        safetyCheck: "Wear nitrile gloves and safety goggles when handling sanitizer concentrates.",
      },
      {
        step: 2,
        title: "Load Produce Basket",
        instruction: "Place maximum 15 kg raw produce per perforated stainless crate. Submerge basket into wash tank.",
        safetyCheck: "Do not overfill basket to allow complete liquid circulation around each vegetable/fruit.",
      },
      {
        step: 3,
        title: "Activate Dip Timer",
        instruction: "Press green START timer. Wait for 120-second buzzer before lifting to drip rack.",
        safetyCheck: "Allow 60 seconds dripping before transferring to inspection table.",
      },
    ],
    provenance: "SOURCE",
  },
  {
    id: "MCH-03",
    name: "Modular Packaging & Heat-Sealing Line",
    category: "Packaging",
    status: "running",
    healthScore: 94,
    oee: 91.2,
    powerKw: 1.85,
    runtimeHours: 940,
    lastServiceDate: "2026-09-05",
    nextServiceHours: 160,
    energySavingVsBaseline: "Impulse heating draws power only during 1.2s seal cycle",
    metrics: [
      { label: "Seal Jaw Temp", value: "146", nominal: "140 - 152", unit: "°C", status: "ok" },
      { label: "Pneumatic Pressure", value: "3.2", nominal: "3.0 - 3.5", unit: "bar", status: "ok" },
      { label: "Dwell Time", value: "1.25", nominal: "1.2 - 1.4", unit: "sec", status: "ok" },
      { label: "Throughput Rate", value: "24", nominal: "20 - 26", unit: "packs/min", status: "ok" },
      { label: "Vacuum Gauge", value: "-0.82", nominal: "-0.75 - -0.85", unit: "bar", status: "ok" },
    ],
    pokaYokeGuides: [
      "Physical alignment jig ensures pouch collar fits snugly into sealing jaws with 5mm margin.",
      "Dual optical sensors abort heat cycle if worker fingers are within 80mm of the sealing clamp.",
      "Teflon tape wear indicator turns orange when replacement is required after 10,000 cycles.",
    ],
    sopSteps: [
      {
        step: 1,
        title: "Check Jaw Temperature & Cleanliness",
        instruction: "Verify digital PID display reads 145°C ± 5°C. Wipe heating element with dry micro-fiber cloth.",
        safetyCheck: "Hot surface hazard: never touch sealing jaw with bare skin.",
      },
      {
        step: 2,
        title: "Position Pouch on Alignment Jig",
        instruction: "Slide filled pouch against bottom stop. Ensure sealing lip is flat with zero wrinkles.",
        safetyCheck: "Ensure package headspace does not exceed 25mm to avoid pouch burst.",
      },
      {
        step: 3,
        title: "Execute Vacuum & Seal Stroke",
        instruction: "Depress foot pedal switch. Hold until vacuum nozzle retracts and audible seal click sounds.",
        safetyCheck: "Inspect first pack of every batch using the 5-point burst seal test.",
      },
    ],
    provenance: "SOURCE",
  },
  {
    id: "MCH-04",
    name: "S4S Solar Conduction Dryer Unit",
    category: "Drying",
    status: "running",
    healthScore: 98,
    oee: 93.0,
    powerKw: 0.12, // 12V DC solar fan only
    runtimeHours: 2150,
    lastServiceDate: "2026-08-20",
    nextServiceHours: 350,
    energySavingVsBaseline: "Zero grid power requirement; utilizes direct solar thermal conduction",
    metrics: [
      { label: "Bed Temp", value: "54.2", nominal: "50 - 58", unit: "°C", status: "ok" },
      { label: "Exhaust Humidity", value: "24", nominal: "20 - 35", unit: "% RH", status: "ok" },
      { label: "Moisture Extraction", value: "0.84", nominal: "0.7 - 1.0", unit: "kg/h", status: "ok" },
      { label: "Solar Irradiance", value: "820", nominal: "> 600", unit: "W/m²", status: "ok" },
      { label: "DC Fan Airflow", value: "1.3", nominal: "1.0 - 1.6", unit: "m/s", status: "ok" },
    ],
    pokaYokeGuides: [
      "Color-coded depth gauge ensures produce layer never exceeds 8mm thickness on black absorber sheets.",
      "Solar chimney chimney louvre automatically opens when bed temperature exceeds 60°C to protect food enzymes.",
      "Desiccant silica gel packets auto-dispense at packing exit for dry grains, spices, and ginger flakes.",
    ],
    sopSteps: [
      {
        step: 1,
        title: "Clean Absorber Trays",
        instruction: "Wipe black conduction plates with food-safe ethanol spray. Allow 5 minutes drying.",
        safetyCheck: "Use food-grade sanitized cloths only.",
      },
      {
        step: 2,
        title: "Spread Sliced Produce",
        instruction: "Lay sliced ginger or chillies evenly across mesh. Do not overlap slices.",
        safetyCheck: "Use spreading rake to maintain uniform 8mm bed depth.",
      },
      {
        step: 3,
        title: "Seal UV-Stabilized Canopy",
        instruction: "Latch canopy clips securely to lock greenhouse heat and keep flies and dust outside.",
        safetyCheck: "Check DC fan battery indicator is at or above 12.4V.",
      },
    ],
    provenance: "SOURCE",
  },
  {
    id: "MCH-05",
    name: "Optical & Roller Sizing Sorting Table",
    category: "Grading",
    status: "alert", // DEMO FAULT
    healthScore: 67,
    oee: 62.4,
    powerKw: 0.45,
    runtimeHours: 520,
    lastServiceDate: "2026-09-01",
    nextServiceHours: 12,
    faultCode: "E-42",
    faultDescription: "Belt Jam & Caliper Dislodged on Roller 2",
    energySavingVsBaseline: "Variable frequency drive motor with auto-shutoff standby",
    metrics: [
      { label: "Roller Speed", value: "0.0", nominal: "0.2 - 0.4", unit: "m/s", status: "crit" },
      { label: "Defect Reject Rate", value: "14.8", nominal: "< 5.0", unit: "%", status: "crit" },
      { label: "Bearing Temp", value: "74", nominal: "< 55", unit: "°C", status: "crit" },
      { label: "Sizing Caliper", value: "Dislodged", nominal: "Locked", unit: "status", status: "crit" },
    ],
    pokaYokeGuides: [
      "Calibrated reference sizing rings mounted on sorting station frame for instant manual size checks.",
      "Distinct color reject chutes prevent graded Class-A produce from mixing with Grade-B or cattle-feed cull.",
      "Automatic torque slip-clutch shuts motor down when produce gets wedged between adjacent rollers.",
    ],
    sopSteps: [
      {
        step: 1,
        title: "Emergency LOTO Shutdown",
        instruction: "Hit Red Emergency Stop button on station pillar. Disconnect 3-phase line plug.",
        safetyCheck: "Lockout Tagout (LOTO) active; never reach into rollers while power is connected.",
      },
      {
        step: 2,
        title: "Clear Roller 2 Jam",
        instruction: "Use non-marring nylon wedge tool to extract wedged tomato/fruit debris from roller 2.",
        safetyCheck: "Inspect rubber drive belt for fraying or tension loss.",
      },
      {
        step: 3,
        title: "Reset Caliper Alignment",
        instruction: "Align feeler gauge to 25mm datum mark and tighten M8 lock bolt.",
        safetyCheck: "Rotate rollers manually by hand to verify smooth, friction-free rotation.",
      },
    ],
    provenance: "PROPOSED",
  },
];

/**
 * Process Tests Suite.
 */
export const PROCESS_TESTS_DATA: ProcessTest[] = [
  {
    id: "TEST-01",
    name: "Incoming Raw Produce Brix & Acidity Test",
    processStep: "Step 1: Sourcing & Receiving Dock",
    category: "Chemical",
    requiredRank: 2,
    nominalRange: "11.5 - 14.0",
    unit: "°Brix",
    lastTestedAt: "2026-09-13 14:15",
    testedBy: "Priya Sharma (Rank 2)",
    currentValue: 12.8,
    status: "pass",
    cpk: 1.42,
    procedure: "Crush 3 sample fruits from bottom, middle, and top of delivery crate. Place 2 drops of clear juice on optical refractometer prism. View through eyepiece at 20°C calibrated ambient.",
    correctiveAction: "If Brix < 11.0, flag batch for secondary ripening or divert to pulp vinegar processing. Reject if fungal decay exceeds 2%.",
    provenance: "SOURCE",
  },
  {
    id: "TEST-02",
    name: "Wash Basin Sanitizing Active Chlorine ppm",
    processStep: "Step 2: Cleansing & Sanitizing Station",
    category: "Chemical",
    requiredRank: 2,
    nominalRange: "100 - 150",
    unit: "ppm Cl",
    lastTestedAt: "2026-09-13 13:40",
    testedBy: "Priya Sharma (Rank 2)",
    currentValue: 108,
    status: "pass",
    cpk: 1.35,
    procedure: "Immerse digital test electrode or chemical test strip into agitated tank center for 10 seconds. Read active chlorine concentration.",
    correctiveAction: "If ppm < 100, add 50ml sodium hypochlorite concentrate. If ppm > 150, flush tank with fresh potable water to prevent chemical skin burn on produce.",
    provenance: "SOURCE",
  },
  {
    id: "TEST-03",
    name: "Pre-Cooling Pulp Temperature & Thermal Pull-Down",
    processStep: "Step 3: Receiving Dock & Shade Pre-Cooling",
    category: "Thermal",
    requiredRank: 2,
    nominalRange: "16.0 - 20.0",
    unit: "°C core",
    lastTestedAt: "2026-09-13 14:30",
    testedBy: "Priya Sharma (Rank 2)",
    currentValue: 18.2,
    status: "pass",
    cpk: 1.28,
    procedure: "Insert calibrated probe thermometer 40mm into geometric center of largest fruit/produce item under shade netting. Log pull-down time after 30 mins shade resting.",
    correctiveAction: "If core temp > 22°C, engage hydro-cooling cold water mist bath immediately before chamber entry to relieve refrigeration compressor thermal surge.",
    provenance: "SOURCE",
  },
  {
    id: "TEST-04",
    name: "Packaging Pouch Vacuum Leak & Burst Pressure Test",
    processStep: "Step 5: Packaging Material Fit & Protection",
    category: "Physical",
    requiredRank: 2,
    nominalRange: "2.8 - 3.6",
    unit: "bar burst",
    lastTestedAt: "2026-09-13 15:00",
    testedBy: "Priya Sharma (Rank 2)",
    currentValue: 3.25,
    status: "pass",
    cpk: 1.48,
    procedure: "Place sealed pouch inside acrylic vacuum desiccator chamber filled with colored water. Draw vacuum to -0.8 bar for 60 seconds. Inspect for stream of micro-bubbles originating from heat-seal seam.",
    correctiveAction: "If bubbles emerge along seal line, replace PTFE Teflon jaw cover tape and recalibrate sealing dwell time by +0.15s.",
    provenance: "SOURCE",
  },
  {
    id: "TEST-05",
    name: "Cold Room Temperature Excursion & Gradient Audit",
    processStep: "Step 6: Storage & Inventory (Cold Chain)",
    category: "Thermal",
    requiredRank: 3,
    nominalRange: "4.0 - 6.5",
    unit: "°C ambient",
    lastTestedAt: "2026-09-13 15:10",
    testedBy: "Amit Patel (Rank 3)",
    currentValue: 5.1,
    status: "pass",
    cpk: 1.55,
    procedure: "Download Bluetooth/USB IoT logger CSV data. Analyze 24-hour continuous temperature curve for degree-hour excursions above 8.0°C limit.",
    correctiveAction: "If excursion > 2 consecutive hours above 8°C, execute emergency stock FEFO re-indexing and check door sealing flaps.",
    provenance: "SOURCE",
  },
  {
    id: "TEST-06",
    name: "Food Contact Surface ATP Microbial Hygiene Swab",
    processStep: "Step 4: Processing Table & Conveyor",
    category: "Microbial",
    requiredRank: 2,
    nominalRange: "< 30",
    unit: "RLU",
    lastTestedAt: "2026-09-13 11:00",
    testedBy: "Priya Sharma (Rank 2)",
    currentValue: 18,
    status: "pass",
    cpk: 1.62,
    procedure: "Swab a 10cm x 10cm grid area of cutting board and sorting chute. Insert swab into luminometer chamber and read Relative Light Units (RLU).",
    correctiveAction: "If RLU > 30, stop line and perform sanitizing foam wash with quaternary ammonium compound. Reswab before restarting batch.",
    provenance: "INFERENCE",
  },
];

export const INVENTORY_CHAMBERS: InventoryChamber[] = [
  {
    id: "CHAMBER-A",
    name: "Cold Room A (Pre-Cooling & Inbound)",
    type: "Pre-Cooling Intake",
    tempC: 2.2,
    targetTempC: "1.5 - 3.5°C",
    humidityPct: 92,
    targetHumidityPct: "90 - 95%",
    capacityCrates: 40,
    occupiedCrates: 28,
    excursionsToday: 0,
    assetTier: "Asset Light",
    provenance: "SOURCE",
  },
  {
    id: "CHAMBER-B",
    name: "Cold Room B (Central High-Bay FEFO)",
    type: "High-Bay FEFO Cold Storage",
    tempC: 0.8,
    targetTempC: "-0.5 - 2.0°C",
    humidityPct: 94,
    targetHumidityPct: "92 - 96%",
    capacityCrates: 80,
    occupiedCrates: 56,
    excursionsToday: 0,
    assetTier: "Asset Light",
    provenance: "SOURCE",
  },
  {
    id: "CHAMBER-C",
    name: "Cold Room C (Finished Goods & Blast)",
    type: "Finished Goods & Blast Chilling",
    tempC: 3.2,
    targetTempC: "2.0 - 4.0°C",
    humidityPct: 88,
    targetHumidityPct: "85 - 90%",
    capacityCrates: 40,
    occupiedCrates: 16,
    excursionsToday: 0,
    assetTier: "Asset Light",
    provenance: "SOURCE",
  },
  {
    id: "CHAMBER-D",
    name: "Dispatch Dock Staging Apron",
    type: "Ambient Buffer",
    tempC: 18.5,
    targetTempC: "16.0 - 20.0°C",
    humidityPct: 65,
    targetHumidityPct: "50 - 70%",
    capacityCrates: 30,
    occupiedCrates: 12,
    excursionsToday: 0,
    assetTier: "Low Investment",
    provenance: "SOURCE",
  },
];

/**
 * FEFO Inventory.
 */
export const FEFO_CRATES_DATA: FefoCrateItem[] = [
  {
    id: "LOT-TOM-901",
    commodity: "Ripe Tomatoes (Hybrid)",
    batchLot: "B-2026-0912-A",
    receivedDate: "2026-09-12",
    expiryDate: "2026-09-17",
    remainingShelfLifeDays: 3,
    initialShelfLifeDays: 8,
    chamberId: "CHAMBER-A",
    status: "expiring_soon",
    abcCategory: "A",
    crateQuantity: 18,
    estimatedValueRupees: 21600,
  },
  {
    id: "LOT-MNG-902",
    commodity: "Totapuri Mango Slices",
    batchLot: "B-2026-0913-B",
    receivedDate: "2026-09-13",
    expiryDate: "2026-09-22",
    remainingShelfLifeDays: 8,
    initialShelfLifeDays: 10,
    chamberId: "CHAMBER-A",
    status: "fresh",
    abcCategory: "A",
    crateQuantity: 26,
    estimatedValueRupees: 31200,
  },
  {
    id: "LOT-CHI-903",
    commodity: "Green Chilli (Grade 1)",
    batchLot: "B-2026-0911-C",
    receivedDate: "2026-09-11",
    expiryDate: "2026-09-25",
    remainingShelfLifeDays: 11,
    initialShelfLifeDays: 16,
    chamberId: "CHAMBER-B",
    status: "fresh",
    abcCategory: "B",
    crateQuantity: 24,
    estimatedValueRupees: 19200,
  },
  {
    id: "LOT-GNG-904",
    commodity: "Dried Ginger Flakes",
    batchLot: "B-2026-0828-D",
    receivedDate: "2026-08-28",
    expiryDate: "2027-02-28",
    remainingShelfLifeDays: 165,
    initialShelfLifeDays: 180,
    chamberId: "CHAMBER-C",
    status: "fresh",
    abcCategory: "C",
    crateQuantity: 38,
    estimatedValueRupees: 45600,
  },
  {
    id: "LOT-SPN-905",
    commodity: "Baby Spinach (Pre-Cooled)",
    batchLot: "B-2026-0913-E",
    receivedDate: "2026-09-13",
    expiryDate: "2026-09-15",
    remainingShelfLifeDays: 1,
    initialShelfLifeDays: 3,
    chamberId: "CHAMBER-A",
    status: "critical",
    abcCategory: "A",
    crateQuantity: 8,
    estimatedValueRupees: 6400,
  },
];

/**
 * Supply Batches.
 */
export const SUPPLY_BATCHES_DATA: SupplyBatch[] = [
  {
    id: "BAT-101",
    farmerOrFpo: "Kisan Unnati FPO (42 Smallholders)",
    district: "Nashik, MH",
    commodity: "Tomatoes (Processing Grade)",
    quantityCrates: 40,
    scheduledArrival: "Today 08:30",
    staggerSlot: "08:00 - 10:00",
    farmGateTempC: 21.5,
    demandMatched: true,
    scorecardRating: 4.8,
    rejectionHistoryPct: 1.8,
  },
  {
    id: "BAT-102",
    farmerOrFpo: "Savitribai Women SHG Cluster",
    district: "Pune Rural, MH",
    commodity: "Green Chillies & Ginger",
    quantityCrates: 30,
    scheduledArrival: "Today 11:00",
    staggerSlot: "10:30 - 12:30",
    farmGateTempC: 23.0,
    demandMatched: true,
    scorecardRating: 4.6,
    rejectionHistoryPct: 2.4,
  },
  {
    id: "BAT-103",
    farmerOrFpo: "Godavari Agro Collective",
    district: "Ahmednagar, MH",
    commodity: "Totapuri Raw Mangoes",
    quantityCrates: 30,
    scheduledArrival: "Today 14:30",
    staggerSlot: "14:00 - 16:00",
    farmGateTempC: 24.5,
    demandMatched: false,
    scorecardRating: 4.1,
    rejectionHistoryPct: 4.5,
  },
];

/**
 * Cash Flow Data.
 */
export const CASH_FLOW_DATA: CashFlowMetrics = {
  workingCapitalBalance: 524000,
  dailyRevenue: 135000,
  dailyOperatingCosts: 78000,
  inventoryHoldingValue: 124000,
  baselineSpoilageLossRupees: 33600,
  optimizedSpoilageLossRupees: 8640,
  netDailySavingsRupees: 24960,
  eNwrLoanAvailable: 93000,
  eNwrInterestRatePct: 7.0,
  distressSaleDiscountAvoidedRupees: 37200,
  pmfmeSubsidyClaimedRupees: 350000,
  pmfmeMaxEligibleRupees: 1000000,
  spoilageInsuranceCoveredRupees: 250000,
  provenance: "SOURCE",
};

/**
 * Initial Worker Grievances ("आवाज / Awaaz Grievance Portal").
 * Gives informal and formal factory workers a voice to report safety hazards,
 * PPE shortages, wage disputes, or machine breakdowns with voice audio recording and playback!
 */
export const INITIAL_GRIEVANCES: WorkerGrievance[] = [
  {
    id: "GRV-101",
    workerName: "Ramesh Kumar",
    rank: 1,
    category: "Cold Exposure / PPE",
    transcript:
      "Thermal gloves in Chamber A are damp from moisture; workers need replacement insulated cold jackets for the 4°C transfer shift.",
    timestamp: "Today 13:45",
    status: "Action Taken",
    audioRecorded: true,
    priority: "High",
  },
  {
    id: "GRV-102",
    workerName: "Sunita Devi",
    rank: 1,
    category: "Machine Breakdown",
    transcript:
      "Sorting table MCH-05 motor guard vibration is rattling violently and belt is slipping dangerously on roller 2.",
    timestamp: "Today 14:12",
    status: "Under Review",
    audioRecorded: true,
    priority: "Urgent",
  },
  {
    id: "GRV-103",
    workerName: "Kavita Bai",
    rank: 1,
    category: "Hygiene & Washroom",
    transcript:
      "Handwash station sanitizer dispenser near Dip Tank 2 was empty during morning changeover. Refill required for FSSAI hygiene audit.",
    timestamp: "Today 11:20",
    status: "Resolved",
    audioRecorded: false,
    priority: "Medium",
  },
];

/**
 * Helper to build live plant notifications.
 * Demonstrates immediate visual feedback for the MCH-05 demo fault,
 * cold storage FEFO critical items, and procurement mismatch.
 */
export function getPlantNotifications(): PlantAlert[] {
  const alerts: PlantAlert[] = [];

  const faultMachine = MACHINES_DATA.find((m) => m.status === "alert");
  if (faultMachine) {
    alerts.push({
      id: `alert-${faultMachine.id}`,
      severity: "critical",
      title: `${faultMachine.name} needs attention`,
      detail: `${faultMachine.faultCode ?? "Alert"}: ${faultMachine.faultDescription ?? "Fault detected"} · health ${faultMachine.healthScore}%`,
      time: "2 min ago",
      machineId: faultMachine.id,
      actionTab: "machines",
      actionLabel: "Inspect",
    });
  }

  const critItem = FEFO_CRATES_DATA.find((item) => item.status === "critical");
  if (critItem) {
    alerts.push({
      id: `alert-fefo-${critItem.id}`,
      severity: "critical",
      title: `FEFO Warning: ${critItem.commodity}`,
      detail: `Lot ${critItem.batchLot} has only ${critItem.remainingShelfLifeDays} day shelf-life remaining in ${critItem.chamberId}`,
      time: "25 min ago",
      actionTab: "inventory",
      actionLabel: "Prioritize",
    });
  }

  const unmatchedBatch = SUPPLY_BATCHES_DATA.find((b) => !b.demandMatched);
  if (unmatchedBatch) {
    alerts.push({
      id: `alert-scm-${unmatchedBatch.id}`,
      severity: "warn",
      title: `Sourcing Notice: Batch ${unmatchedBatch.id}`,
      detail: `${unmatchedBatch.commodity} exceeds confirmed orders. Route to buffer.`,
      time: "1 h ago",
      actionTab: "supply",
      actionLabel: "Review",
    });
  }

  return alerts;
}
